print("FUND MASTER")
print(fund.columns.tolist())
performance = pd.read_csv(RAW_DATA / "07_scheme_performance.csv")
print("SCHEME PERFORMANCE")
print(performance.columns.tolist())
transactions = pd.read_csv(RAW_DATA / "08_investor_transactions.csv")
print("TRANSACTIONS")
print(transactions.columns.tolist())
nav = pd.read_csv(RAW_DATA / "02_nav_history.csv")
print("NAV")
print(nav.columns.tolist())